### ISSUE TITLE
No_repo option needs to have this error fixed

### ISSUE THREAD

**Issue by tsikerdekis** [athina-edu/athina#22]
```
athina_1      | 2019-04-01 19:22:06,560 - INFO - Tests failed:
athina_1      |  Traceback (most recent call last):
athina_1      |   File "test-participation.py", line 12, in <module>
athina_1      |     due_date = dateutil.parser.parse(sys.argv[2]).isocalendar()[1]
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/dateutil/parser/_parser.py", line 1358, in parse
athina_1      |     return DEFAULTPARSER.parse(timestr, **kwargs)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/dateutil/parser/_parser.py", line 649, in parse
athina_1      |     raise ValueError("Unknown string format:", timestr)
athina_1      | ValueError: ('Unknown string format:', "'2100-01-01T00:00:00']")

```

**Comment by tsikerdekis** [comment]
Actually, this is a test script error but perhaps Athina needs to pass the UTC deadline version.

**Comment by tsikerdekis** [comment]
Fixed and extra params where ajusted
