### ISSUE TITLE
Norepo assignment generates this after some iterations

### ISSUE THREAD

**Issue by tsikerdekis** [athina-edu/athina#24]
```
athina_1      | FileNotFoundError: [Errno 2] No such file or directory: '/code/athina.log.3'
athina_1      | Call stack:
athina_1      |   File "/usr/local/bin/athina-cli", line 193, in <module>
athina_1      |     main()
athina_1      |   File "/usr/local/bin/athina-cli", line 155, in main
athina_1      |     tester.start_testing_db()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 338, in start_testing_db
athina_1      |     user_object_results = self.parallel_map(user_ids)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 343, in parallel_map
athina_1      |     compute_pool = multiprocessing.Pool(processes=self.configuration.processes)
athina_1      |   File "/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
athina_1      |     context=self.get_context())
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
athina_1      |     self._repopulate_pool()
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
athina_1      |     self._wrap_exception)
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
athina_1      |     w.start()
athina_1      |   File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
athina_1      |     self._popen = self._Popen(self)
athina_1      |   File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
athina_1      |     return Popen(process_obj)
athina_1      |   File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
athina_1      |     self._launch(process_obj)
athina_1      |   File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
athina_1      |     code = process_obj._bootstrap()
athina_1      |   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
athina_1      |     self.run()
athina_1      |   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
athina_1      |     self._target(*self._args, **self._kwargs)
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
athina_1      |     result = (True, func(*args, **kwds))
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
athina_1      |     return list(map(*args))
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 149, in process_student_assignment
athina_1      |     self.logger.logger.info(">> No changes or past due date")
athina_1      | Message: '>> No changes or past due date'
athina_1      | Arguments: ()
athina_1      | 2019-04-02 05:59:48,021 - INFO - >> No changes or past due date
athina_1      | 2019-04-02 05:59:48,023 - INFO - >> No changes or past due date
athina_1      | multiprocessing.pool.RemoteTraceback:
athina_1      | """
athina_1      | Traceback (most recent call last):
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
athina_1      |     result = (True, func(*args, **kwds))
athina_1      |   File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
athina_1      |     return list(map(*args))
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 75, in process_student_assignment
athina_1      |     self.logger.create_logger()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/logger.py", line 26, in create_logger
athina_1      |     self._safe_add_handler(fh)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/logger.py", line 44, in _safe_add_handler
athina_1      |     if single_handler.stream.name == handler.stream.name:
athina_1      | AttributeError: 'NoneType' object has no attribute 'name'

```

**Comment by tsikerdekis** [comment]
fixed in 877984815b6820229fb0b96a40af6d180a6a4737

This was racing condition issue with the logger. Long story short, logs rotate under single thread and under parallel threads logs are recreated as non-rotational (filehandler). Any exceeded byte space gets taken care of once the map() ends and the main process recreates a rotational version of the logger object.
