### ISSUE TITLE
Moss bug

### ISSUE THREAD

**Issue by tsikerdekis** [athina-edu/athina#26]
```
athina_1      | 2019-04-05 09:00:56,730 - INFO - Checking for plagiarism...
athina_1      | 2019-04-05 09:00:56,730 - DEBUG - [3778480, 3787738, 3888498]
athina_1      | perl /usr/local/lib/python3.6/dist-packages/athina/mossnet.pl -l python -d /code/athina_files/1/CISS 340 SQL 1/repodata4688430/u3778480/*.sql /code/athina_files/1/CISS 340 SQL 1/repodata4688430/u3787738/*.sql /code/athina_files/1/CISS 340 SQL 1/repodata4688430/u3888498/*.sql
athina_1      | b'File /code/athina_files/1/CISS does not exist. Request not sent.\n'
athina_1      | b'Checking files . . . \n'
athina_1      | Checking files . . .
athina_1      | Traceback (most recent call last):
athina_1      |   File "/usr/local/bin/athina-cli", line 194, in <module>
athina_1      |     main()
athina_1      |   File "/usr/local/bin/athina-cli", line 160, in main
athina_1      |     tester.plagiarism_checks_on_users()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 269, in plagiarism_checks_on_users
athina_1      |     comparison_data = plagiarism.check_plagiarism(directory_list)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/moss.py", line 51, in check_plagiarism
athina_1      |     text = self.request_url(out.decode("ascii").split("\n")[-2], return_type="text")
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/moss.py", line 78, in request_url
athina_1      |     r = requests.get(url, headers=headers)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 75, in get
athina_1      |     return request('get', url, params=params, **kwargs)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
athina_1      |     return session.request(method=method, url=url, **kwargs)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 519, in request
athina_1      |     prep = self.prepare_request(req)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 462, in prepare_request
athina_1      |     hooks=merge_hooks(request.hooks, self.hooks),
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 313, in prepare
athina_1      |     self.prepare_url(url, params)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 387, in prepare_url
athina_1      |     raise MissingSchema(error)
athina_1      | requests.exceptions.MissingSchema: Invalid URL 'Checking files . . . ': No schema supplied. Perhaps you meant http://Checking files . . . ?
athinaoneclickrun_athina_1 exited with code 1

```

**Comment by tsikerdekis** [comment]
fixed in ca0f1a300bb09a25367d082f0d58e3ca31a0878e
