### ISSUE TITLE
SQLite needs reconnect procudere on exception

### ISSUE THREAD

**Issue by tsikerdekis** [athina-edu/athina#32]
athina_1      |   File "/usr/local/bin/athina-cli", line 193, in <module>
athina_1      |     main()
athina_1      |   File "/usr/local/bin/athina-cli", line 155, in main
athina_1      |     tester.start_testing_db()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 314, in start_testing_db
athina_1      |     for user in Users.select():
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 4090, in next
athina_1      |     self.cursor_wrapper.iterate()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 4000, in iterate
athina_1      |     row = self.cursor.fetchone()
athina_1      | sqlite3.ProgrammingError: Cannot operate on a closed database.

**Comment by tsikerdekis** [comment]
```
athina_1      | 2019-04-26 22:59:32,341 - 1 - WARNING - Testing script returned warning/error: fatal: your current branch 'master' does not have any commits yet
athina_1      |
athina_1      | Traceback (most recent call last):
athina_1      |   File "/usr/local/bin/athina-cli", line 197, in <module>
athina_1      |     main()
athina_1      |   File "/usr/local/bin/athina-cli", line 155, in main
athina_1      |     tester.start_testing_db()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 314, in start_testing_db
athina_1      |     for user in Users.select():
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 4090, in next
athina_1      |     self.cursor_wrapper.iterate()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 4000, in iterate
athina_1      |     row = self.cursor.fetchone()
athina_1      | sqlite3.ProgrammingError: Cannot operate on a closed database.

```
