### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by tsikerdekis** [athina-edu/athina#43]
```
e_class': 'image', 'media_entry_id': None, 'locked_for_user': False, 'preview_url': None}]}]
athina_1      | 2019-10-19 23:49:46,523 - 1 - DEBUG - Retrieved!
athina_1      | 2019-10-19 23:49:46,530 - 1 - DEBUG - Checking for duplicate urls...
athina_1      | 2019-10-19 23:49:46,532 - 1 - DEBUG - Checked!
athina_1      | 2019-10-19 23:49:46,532 - 1 - INFO - Pre-fetching all user repositories
athina_1      | Traceback (most recent call last):
athina_1      |   File "/usr/local/bin/athina-cli", line 202, in <module>
athina_1      |     main()
athina_1      |   File "/usr/local/bin/athina-cli", line 97, in main
athina_1      |     core_iteration(configuration, user_data)
athina_1      |   File "/usr/local/bin/athina-cli", line 167, in core_iteration
athina_1      |     tester.start_testing_db()
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/tester/tester.py", line 292, in start_testing_db
athina_1      |     self.repository.check_repository_changes(user.user_id)
athina_1      |   File "/usr/local/lib/python3.6/dist-packages/athina/git.py", line 96, in check_repository_changes
athina_1      |     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
athina_1      |   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
athina_1      |     restore_signals, start_new_session)
athina_1      |   File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
athina_1      |     restore_signals, start_new_session, preexec_fn)
athina_1      | BlockingIOError: [Errno 11] Resource temporarily unavailable
athinaoneclickrun_athina_1 exited with code 1
```

**Comment by tsikerdekis** [comment]
This occurs under extraordinary circumstances. Hasn't occurred on a live instance since.
